### ISSUE TITLE
Clarify license

### ISSUE THREAD

**Issue by cmungall** [MolGenie/ontology#1]
the LICENSE file is Artistic (which is intended for code)

the README claims dual license with code under Artistic and data/content under CC-BY. However, there is no code in the repo, only an obo file!

I suggest simplifying and switching to an unambiguous CC-BY license

**Comment by schymane** [comment]
Clarified in https://github.com/MolGenie/ontology/commit/1def819a9a0c3af84cf1127d7c54ec9969e8932b
