### ISSUE TITLE
fix syntax

### ISSUE THREAD

**Issue by cmungall** [MolGenie/ontology#2]
the obo format doesn't conform to the standard and will not parse with any obo parser.

I think you want to be making use of `property_value` and `relationship` more

I also recommend using prefixed IDs

**Comment by schymane** [comment]
@cmungall can you please provide more details? @PaulThiessen is able to parse versions of this obo and create [this](https://pubchem.ncbi.nlm.nih.gov/classification/#hid=134), if you can provide details and examples we can try to address your concerns but no clue where to start based on those comments ...

**Comment by lutzweber** [comment]
@cmungall your comment is not clear to me - the ontology uses prefixed IDs such as MGNxxxxxx - the IDs with 12 digit numbers are actually compound instances of respective classes as shown in the PubChem browser. Did you look into the GitHub repository? The ontology actually loads with the Stanford WebProtegé (https://protegewiki.stanford.edu/wiki/WebProtege). This is an open access webserver based OBO ontology editor used by many people. Please contact Matthew Horridge there - he has implemented a similar ontology with more than 22 million nodes in collaboration with BASF using WebProtegé. However, I agree that many OBO Editors (which one are you using?) do not implement fully the 1.2 OBO Format definitions (for example the possibilities to use extended DbxRef for Synonyms etc. In these cases we typically provide a down-graded version. If you like we could do this and check it with your respective editor.

**Comment by lutzweber** [comment]
@cmungall I have added a Protégé (Mac and PC) compatible OBO and RDF version to GitHub in addition to the OBO 1.2 format version. Hope this works for you.

**Comment by cmungall** [comment]
Thanks! This now parses using standard libraries such as the OWLAPI and pronto.

The IDs are still a problem. The prefix should be separated from the local ID using a `:`. I also recommend registering the prefix in [bioregistry](https://bioregistry.io/) or bioportal (MGN is not yet taken).

**Comment by cmungall** [comment]
Or you may want to use MOCO IDs...
